import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require = createRequire(new URL('../../package.json', import.meta.url));
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, executablePath: process.env.BROWSER_EXECUTABLE || undefined });
const target = '0x019164316504adec856ef1ceed51ca00fd79ea3120ebbef6d418e1824c2e91ed';
const base = process.env.WEB_URL || 'http://127.0.0.1:4174';
try {
  const page = await browser.newPage({ viewport: { width: 1536, height: 1024 } });
  // Read-only production smoke, followed by explicit browser-only interaction data.
  // Protected reference orders may expire; never create on-chain orders for UI QA.
  const summary = await (await page.request.get(`${base}/api/v1/market/${target}`)).json();
  const history = await (await page.request.get(`${base}/api/v1/market/${target}/orders?limit=1`)).json();
  const seed = { ...history.items[0], side: 'buy', status: 'open', expiry: Math.floor(Date.now() / 1000) + 21600 };
  assert.ok(seed.orderId);
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(`${base}/market`);
  await page.getByRole('heading', { name: 'Market', exact: true }).waitFor();
  const liveMarkets = await (await page.request.get(`${base}/api/v1/market?limit=100`)).json();
  assert.ok(Array.isArray(liveMarkets.items));
  await page.route('**/api/v1/market?*', route => route.fulfill({ json: { items: [{ ...summary, openOrders: 2 }] } }));
  await page.route('**/api/v1/market/*/orders?*', route => route.fulfill({ json: { items: [{ ...seed, side: new URL(route.request().url()).searchParams.get('side') || 'buy' }] } }));
  await page.reload();
  await page.locator('.market-discovery-card').first().waitFor();
  const title = await page.getByRole('heading', { name: 'Market', exact: true }).boundingBox();
  const search = await page.getByRole('textbox', { name: 'Search markets' }).boundingBox();
  assert.ok(Math.abs(title.y - search.y) < 40);
  assert.equal(await page.locator('.market-directory-table').count(), 0, 'directory uses token-market cards');
  assert.equal(await page.locator('.discovery-card-footer').count(), 0, 'directory cards have no separate action footer');
  assert.equal(await page.getByText('View market', { exact: true }).count(), 0, 'whole-card link needs no repeated CTA');
  const firstCard = page.locator('.market-discovery-card').first();
  const nameBox = await firstCard.locator('h3').boundingBox();
  const symbolBox = await firstCard.locator('.discovery-symbol').boundingBox();
  const addressBox = await firstCard.locator('code').boundingBox();
  const orderCountBox = await firstCard.locator('.discovery-order-count').boundingBox();
  assert.ok(Math.abs(nameBox.y - symbolBox.y) < 6, 'name and symbol share the title row');
  assert.ok(Math.abs(addressBox.y - orderCountBox.y) < 6, 'address and order count share the metadata row');
  assert.ok(addressBox.y >= nameBox.y + nameBox.height, 'metadata sits below the title row');
  assert.equal(await page.getByText('Prices in ETH per token', { exact: true }).count(), 1);
  assert.equal(await page.locator('.discovery-grid').evaluate(el => getComputedStyle(el).gridTemplateColumns.split(' ').length), 4);
  if (process.env.QA_DIR) await page.screenshot({ path: `${process.env.QA_DIR}/market-directory.png`, fullPage: true });
  await page.getByRole('textbox', { name: 'Search markets' }).fill(target.toUpperCase().replace('0X', '0x'));
  assert.equal(await page.locator('.market-discovery-card').count(), 1, 'exact address search isolates a market');
  await page.locator('.market-discovery-card').click();
  await page.getByRole('button', { name: 'Sell OMS', exact: true }).waitFor();
  await page.getByRole('link', { name: 'All markets', exact: true }).click();
  await page.getByRole('textbox', { name: 'Search markets' }).fill('no-such-token');
  await page.getByText('No matching active market', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'List tokens', exact: true }).click();
  await page.getByRole('dialog').getByRole('textbox', { name: 'Contract address' }).fill(target);
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('dialog', { name: 'List tokens' }).getByRole('textbox', { name: /^Amount/ }).waitFor();
  await page.keyboard.press('Escape');
  await page.goto(`${base}/market/${target}`);
  await page.getByRole('button', { name: 'Sell OMS', exact: true }).waitFor();
  assert.equal(await page.locator('.table-pagination').count(), 0, 'single pages hide pagination');
  assert.equal(await page.locator('.market-orderbook, .market-workspace').count(), 0, 'no order book or permanent sidebar');
  if (process.env.QA_DIR) await page.screenshot({ path: `${process.env.QA_DIR}/market-live.png`, fullPage: true });
  await page.getByRole('button', { name: 'Sell OMS', exact: true }).click();
  await page.getByRole('dialog', { name: 'Sell OMS' }).waitFor();
  await page.getByText('You receive', { exact: true }).last().waitFor();
  assert.ok((await page.getByRole('dialog').innerText()).includes('This order is filled in full.'));
  if (process.env.QA_DIR) await page.screenshot({ path: `${process.env.QA_DIR}/market-confirm.png` });
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('dialog').count(), 0);
  assert.equal(await page.getByRole('button', { name: 'Sell OMS', exact: true }).evaluate(el => el === document.activeElement), true, 'focus restored to order action');
  await page.getByRole('button', { name: 'Sell orders', exact: true }).click();
  await page.getByRole('button', { name: 'Buy OMS', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Buy OMS', exact: true }).click();
  await page.getByRole('dialog', { name: 'Buy OMS' }).waitFor();
  await page.getByText('Wallet payment', { exact: true }).waitFor();
  if (process.env.QA_DIR) await page.screenshot({ path: `${process.env.QA_DIR}/market-purchase.png` });
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Activity', exact: true }).click();
  assert.equal(await page.locator('.market-order-row').count(), 0, 'activity does not stack below orders');
  await page.getByRole('button', { name: 'My orders', exact: true }).click();
  await page.getByText('Connect to view and manage your orders.', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'List tokens', exact: true }).click();
  await page.getByRole('dialog', { name: 'List tokens' }).waitFor();
  assert.equal(await page.getByRole('dialog').getByRole('button', { name: 'Sell', exact: true }).getAttribute('aria-pressed'), 'true');
  await page.getByRole('dialog').getByRole('button', { name: 'Buy', exact: true }).click();
  await page.getByRole('dialog', { name: 'Make an offer' }).waitFor();
  await page.getByRole('dialog').getByRole('button', { name: 'Sell', exact: true }).click();
  await page.getByRole('textbox', { name: /^Amount/ }).fill('1000');
  await page.getByRole('textbox', { name: /^Price per token/ }).fill('0.000001');
  await page.getByRole('dialog').getByText('0.001 ETH', { exact: true }).waitFor();
  if (process.env.QA_DIR) await page.screenshot({ path: `${process.env.QA_DIR}/market-create.png` });
  await page.getByRole('button', { name: 'Advanced settings', exact: true }).click();
  await page.getByText('VM execution budget', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Advanced settings', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Connect wallet', exact: true }).focus();
  await page.keyboard.press('Tab');
  assert.equal(await page.getByRole('button', { name: 'Close dialog' }).evaluate(el => el === document.activeElement), true, 'focus trapped in modal');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForFunction(() => document.documentElement.scrollWidth === innerWidth);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  if (process.env.QA_DIR) await page.screenshot({ path: `${process.env.QA_DIR}/market-mobile-modal.png` });
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Buy orders', exact: true }).click();
  await page.getByRole('button', { name: 'Sell OMS', exact: true }).waitFor();
  if (process.env.QA_DIR) await page.screenshot({ path: `${process.env.QA_DIR}/market-mobile.png`, fullPage: true });
  await page.goto(`${base}/market`);
  await page.locator('.market-discovery-card').first().waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.equal(await page.locator('.discovery-grid').evaluate(el => getComputedStyle(el).gridTemplateColumns.split(' ').length), 1);
  if (process.env.QA_DIR) await page.screenshot({ path: `${process.env.QA_DIR}/market-directory-mobile.png`, fullPage: true });
  assert.deepEqual(errors, []);
  console.log('PASS: live directory smoke; browser-fixture search, default buy orders, sell switch, wallet empty state, advanced settings, single-page hidden, 390px responsive');
  const fixture = await browser.newPage({ viewport: { width: 1536, height: 1024 } });
  let socket;
  await fixture.routeWebSocket('**/v1/ws', ws => { socket = ws; });
  const calls = [];
  await fixture.route('**/api/v1/market/*/orders?*', async route => {
    const url = new URL(route.request().url());
    const cursor = url.searchParams.get('cursor');
    calls.push(cursor);
    const items = cursor ? [] : Array.from({ length: 25 }, (_, i) => ({ ...seed, orderId: String(i + 1), amount: (BigInt([1000, 2500, 500, 5000][i % 4]) * 10n ** 18n).toString(), unitPriceWei: '1000000000000', priceWei: (BigInt([1000, 2500, 500, 5000][i % 4]) * 1000000000000n).toString(), expiry: Math.floor(Date.now() / 1000) + 21600 }));
    await route.fulfill({ json: { items, ...(cursor ? {} : { nextCursor: 'test-next' }) } });
  });
  await fixture.goto(`${base}/market/${target}`);
  const footer = fixture.locator('.market-gallery-content .table-pagination');
  await footer.waitFor();
  const before = await footer.boundingBox();
  await fixture.locator('.market-gallery-scroll').evaluate(el => { el.scrollTop = el.scrollHeight; });
  const after = await footer.boundingBox();
  assert.equal(before.y, after.y, 'footer stays fixed below scrollable table content');
  await footer.getByRole('button', { name: 'Next page' }).click();
  await footer.getByText('Page 2', { exact: true }).waitFor();
  assert.equal(await footer.getByRole('button', { name: 'Next page' }).isDisabled(), true);
  assert.equal(await footer.getByRole('button', { name: 'Previous page' }).isEnabled(), true, 'empty last page can navigate back');
  assert.ok(calls.includes('test-next'));
  const updated = fixture.waitForResponse(r => r.url().includes('/orders?') && r.url().includes('cursor=test-next'));
  socket.send(JSON.stringify({ type: 'svm.executions' }));
  await updated;
  await footer.getByText('Page 2', { exact: true }).waitFor();
  await footer.getByRole('button', { name: 'Previous page' }).click();
  await footer.getByText('Page 1', { exact: true }).waitFor();
  // A concept-density screenshot uses browser-only fixtures, never writes or submits transactions.
  await fixture.route('**/api/v1/market/*/orders?*', async route => {
    const amounts = [1000, 2500, 500, 5000, 1200, 3000];
    await route.fulfill({ json: { items: amounts.map((n, i) => ({ ...seed, orderId: String(i + 12), amount: (BigInt(n) * 10n ** 18n).toString(), unitPriceWei: '1000000000000', priceWei: (BigInt(n) * 1000000000000n).toString(), expiry: Math.floor(Date.now() / 1000) + 21600 })) } });
  });
  await fixture.reload();
  await fixture.locator('.market-order-row').nth(5).waitFor();
  assert.equal(await fixture.locator('.table-pagination').count(), 0);
  const columns = await fixture.locator('.market-order-row').first().evaluate(el => getComputedStyle(el).gridTemplateColumns.split(' ').length);
  assert.equal(columns, 5, 'orders align in five desktop columns');
  const compactRow = await fixture.locator('.market-order-row').first().boundingBox();
  assert.ok(compactRow.height <= 72, 'order rows stay compact without clipping');
  assert.equal(await fixture.locator('.market-token-heading h1').evaluate(el => getComputedStyle(el).fontSize), '22px');
  assert.equal(await fixture.locator('.market-summary-strip, .market-card-terms, .market-gallery-toolbar').count(), 0, 'no extra summaries or filter chrome');
  assert.equal(await fixture.getByRole('columnheader', { name: 'Total price' }).count(), 1);
  const amountBox = await fixture.locator('.order-amount').first().boundingBox();
  const totalBox = await fixture.locator('.order-total').first().boundingBox();
  assert.ok(Math.abs(amountBox.y - totalBox.y) < 2 && totalBox.x > amountBox.x, 'amount and total sit side by side');
  const makerBox = await fixture.locator('.order-maker').first().boundingBox();
  const actionBox = await fixture.locator('.order-action').first().boundingBox();
  assert.ok(Math.abs(makerBox.y + makerBox.height / 2 - actionBox.y - actionBox.height / 2) < 2, 'maker and action align on desktop');
  assert.equal(await fixture.locator('.order-total .order-value').first().innerText(), '0.001 ETH', 'whole-order total, not unit price');
  await fixture.getByRole('button', { name: 'Make an offer', exact: true }).click();
  assert.equal(await fixture.getByRole('dialog').getByRole('button', { name: 'Buy', exact: true }).getAttribute('aria-pressed'), 'true');
  await fixture.keyboard.press('Escape');
  await fixture.locator('.market-token-heading h1').click();
  if (process.env.QA_DIR) await fixture.screenshot({ path: `${process.env.QA_DIR}/market-gallery.png`, fullPage: true });
  for (const [width, expectedColumns] of [[900, 5], [650, 3], [390, 3], [320, 3]]) {
    await fixture.setViewportSize({ width, height: 844 });
    assert.equal(await fixture.locator('.market-order-row').first().evaluate(el => getComputedStyle(el).gridTemplateColumns.split(' ').length), expectedColumns);
    assert.equal(await fixture.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `no page overflow at ${width}px`);
    if (width <= 650) assert.ok((await fixture.locator('.order-action').first().boundingBox()).height >= 40, 'mobile trading target remains usable');
    if (width === 390 && process.env.QA_DIR) await fixture.screenshot({ path: `${process.env.QA_DIR}/market-list-mobile.png`, fullPage: true });
  }
  await fixture.locator('.order-total strong').first().evaluate(el => { el.textContent = '115792089237316195423570985008687907853269984665640564039457.584007913129639935'; });
  await fixture.locator('.order-amount .order-value span').first().evaluate(el => { el.textContent = 'LONGTOKEN'.repeat(10); });
  assert.equal(await fixture.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'long exact prices and symbols wrap without horizontal overflow');
  await fixture.route('**/api/v1/market/*/orders?*', route => route.fulfill({ json: { items: [{ ...seed, expiry: 1 }] } }));
  await fixture.reload();
  await fixture.locator('.order-action').waitFor();
  assert.equal(await fixture.locator('.order-action').isDisabled(), true, 'expired order action remains disabled');
  await fixture.route('**/api/v1/market/*/orders?*', route => route.fulfill({ json: { items: [] } }));
  await fixture.reload();
  await fixture.getByRole('heading', { name: 'No open orders', exact: true }).waitFor();
  assert.equal(await fixture.locator('.market-order-list, .table-pagination').count(), 0, 'empty state has neither table chrome nor pagination');
  console.log('PASS: 25-row server-cursor fixture, fixed footer, empty last page, previous/next, realtime preserves page');
} finally { await browser.close(); }
